* fix issue when setting datetime or timestamp default values
cakephp/phinx pull request #1864
Opened 2020-08-18 05:10 UTC by dalesmckay

- CURRENT_TIMESTAMP must match the precision of the defined column
	- applies to MySQL 5.6+
	- ref: https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

eg.
        $this->table('test_table')->addColumn('created_at', 'timestamp', ['limit' => 6, 'default' => 'CURRENT_TIMESTAMP'])

2020-08-18 06:40 UTC, dereuromark commented
Can you add a test case?

2020-09-30 09:09 UTC, dereuromark commented
@dalesmckay ping

2020-09-30 12:41 UTC, dalesmckay commented
Sorry, I don't really have time at the moment.
I'm currently using a forked version with my fix via composer-patches.

The official phinx library does not correctly support timestamps with microseconds (at least for MySQL).
Errors will occur due to the default value 'CURRENT_TIMESTAMP' not getting the limit applied.

By default, datetime/timestamp fields only save "seconds":
     2020-09-30 20:33:**13**

However, I need to be able to also access the "microseconds":
     2020-09-30 20:33:**13.931167**


eg.
     If I want to be able to save/fetch datetime fields with 6 digits of microseconds:

```PHP
use Phinx\Migration\AbstractMigration;

class CreateTestTable extends AbstractMigration
{
    public function change() {
        // Create new table
        $this->table('test_table')
             ->addColumn('reason', 'string')
             ->addColumn('created_at', 'timestamp', ['limit' => 6, 'default' => 'CURRENT_TIMESTAMP'])
             ->addColumn('updated_at', 'timestamp', ['limit' => 6, 'default' => 'CURRENT_TIMESTAMP'])
             ->addColumn('deleted_at', 'timestamp', ['limit' => 6, 'null' => true, 'default' => null])
             ->create()
        ;
    }
}
```

This will generate SQL something like:
```MySQL
CREATE TABLE `test_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reason` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

```

However, to avoid syntax error, the SQL should be like:
```MySQL
CREATE TABLE `test_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reason` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

ie.
     CURRENT_TIMESTAMP vs CURRENT_TIMESTAMP(6)

2020-09-30 17:01 UTC, MasterOdin requested changes

2020-09-30 17:01 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PdoAdapter.php
> +            if (str_starts_with($default, 'CURRENT_TIMESTAMP')) {
Should probably either use `strpos($default, 'CURRENT_TIMESTAMP') === 0` or add `symfony/polyfill-php80` to the composer.json dependencies as this function is coming from there and it is a sub-dependency of `symfony/console` (and probably others).

2020-12-05 22:20 UTC, dereuromark commented
Anything that can be done to finalize this for merge at this point?

2021-06-02 09:21 UTC, dereuromark commented
ping @dalesmckay

2021-06-02 10:30 UTC, dalesmckay commented
I don’t have anything more than the MySQL fix from above that I’ve been using.

I’m not using this with any other DB engine.

2021-09-03 11:13 UTC, dereuromark commented
@MasterOdin Shall we close this then?

2022-12-22 15:20 UTC, closed without merging