Implement identity in PostgresAdapter
cakephp/phinx pull request #2085
Opened 2022-04-08 10:13 UTC by ajibarra

Working on #2070 . Implementing IDENTITY for column in PostgresAdapter.

2022-08-25 15:21 UTC, swiffer commented
@MasterOdin any Chance to get this merged for 0.13? Would be great to have Support in cakephp/Migrations at some point. Thanks a Lot!

2022-08-27 04:16 UTC, MasterOdin requested changes

2022-08-27 04:16 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +             datetime_precision, identity_generation
Easy enough I think to change this to:

```php
        $sql = sprintf(
            'SELECT column_name, data_type, udt_name, is_identity, is_nullable,
             column_default, character_maximum_length, numeric_precision, numeric_scale,
             datetime_precision
             %s
             FROM information_schema.columns
             WHERE table_schema = %s AND table_name = %s
             ORDER BY ordinal_position',
            $this->useIdentity ? ', identity_generation' : '',
            $this->getConnection()->quote($parts['schema']),
            $this->getConnection()->quote($parts['table'])
```

and maintain compatibility with any and all PG versions (mostly a thought for redshift)

2022-08-27 04:16 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +//        var_dump($column->getGenerated());
remove?

2022-08-27 04:16 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +    }
As opposed to having this public function just for use in tests, I'd rather we do the same as we do for mysql, and just add an equivalent function to the test suite and use that:

https://github.com/cakephp/phinx/blob/9a6ce1e7fdf0fa4e602ba5875b5bc9442ccaa115/tests/Phinx/Db/Adapter/MysqlAdapterTest.php#L45-L48

It's a bit repetitive, but I'd rather avoid adding new public functions, especially ones that are very adapter specific. Just another thing that gets added for BC, and feels like easier to potentially break.

2022-08-27 04:16 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/PostgresAdapterTest.php
> +    }
Can we combine these two tests into one and use a dataProvider?

2022-08-27 04:16 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/PostgresAdapterTest.php
> +    }
Same here.

2022-08-29 08:06 UTC, dereuromark commented
ping @ajibarra 

Otherwise @swiffer you could also make a new PR from those changes and include the mentioned feedback
Then we can merge an alternative PR here as well.

2022-09-01 10:50 UTC, dereuromark commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +                    'Column type "' . $sqlType . '" is not supported by Postgresql.'
can we use ` for code fencing?

2022-09-01 10:54 UTC, ajibarra commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +                    'Column type "' . $sqlType . '" is not supported by Postgresql.'
sure

2022-09-01 11:32 UTC, ajibarra commented
@MasterOdin changes requested has been pushed. For some reason coverage has decreased. One of the issues reported is because of splitting the exception message to avoid PHP CS warning but I can't find the actual reason for the other one (L105-L106) because connect method is called for sure and that lines are executed so I am out of ideas.

2022-09-16 05:22 UTC, ajibarra commented
> 

@dereuromark Maybe you know?

2022-09-16 05:23 UTC, ajibarra commented
> @MasterOdin changes requested has been pushed. For some reason coverage has decreased. One of the issues reported is because of splitting the exception message to avoid PHP CS warning but I can't find the actual reason for the other one (L105-L106) because connect method is called for sure and that lines are executed so I am out of ideas.

@dereuromark Maybe you know?

2022-09-16 05:30 UTC, MasterOdin commented
The decrease in code coverage is fine. Most likely some of the formatting changes made here touch upon code that's not tested.

2022-09-16 05:32 UTC, ajibarra commented
> The decrease in code coverage is fine. Most likely some of the formatting changes made here touch upon code that's not tested.

Great then, so it is ready to be merged after approval. Thank you @MasterOdin

2022-10-02 14:13 UTC, MasterOdin approved these changes

2022-10-02 14:13 UTC, merged

2022-11-18 12:48 UTC, romanzks commented on src/Phinx/Db/Adapter/PostgresAdapter.php
> +            $this->useIdentity = (float)$db->getAttribute(PDO::ATTR_SERVER_VERSION) >= 10;
I'm not sure if it's the right approach to decide whether to use an `identity` depending on the version of PostgreSQL. This makes it impossible to use the `serial` type to create auto-increment column. These are different things that work in different ways. And one of them does not replace the other. There must be a choice of which auto-increment approach will be used.