support PDO persistent connection
cakephp/phinx pull request #2092
Opened 2022-05-10 22:05 UTC by paulermo

This fixes the ability to use persistent connections by PDO. 
One can set generic PDO attributes (#1904) but the attribute - \PDO::ATTR_PERSISTENT - is useless while setting it by setAttribute after PDO object instantiation:

> Note:
> If you wish to use persistent connections, you must set PDO::ATTR_PERSISTENT in the array of driver options passed to the PDO constructor. If setting this attribute with [PDO::setAttribute()](https://www.php.net/manual/en/pdo.setattribute.php) after instantiation of the object, the driver will not use persistent connections.
[https://www.php.net/manual/en/pdo.connections.php](url)

From the point of view of usage, nothing changes: like other PDO arguments we specify `attr_persistent => true` config option. Before the PDO instatiation this attribute (if specified) is passed to driver options instead of setting in setAttribute after it.

2022-05-11 07:08 UTC, MasterOdin requested changes

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/MysqlAdapterTest.php
> +        $this->assertEquals(true, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertTrue($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/PostgresAdapterTest.php
> +        $this->assertEquals(true, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertTrue($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
> +        $this->assertEquals(true, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertTrue($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/MysqlAdapterTest.php
> +        $this->assertEquals(false, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertFalse($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/PostgresAdapterTest.php
> +        $this->assertEquals(false, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertFalse($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-11 07:08 UTC, MasterOdin commented on tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
> +        $this->assertEquals(false, $adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT));
```suggestion
        $this->assertFalse($adapter->getConnection()->getAttribute(\PDO::ATTR_PERSISTENT);
```

2022-05-21 02:46 UTC, MasterOdin requested changes
Does `attr_persistent` work for SQL Server? If not, would there be any harm in passing it as an option anyway?

If either of the above is "yes", I think it would make sense to lift the code setting this option out of the specific adapters into the `PdoAdapter::createPdoConnection` method, having it be:

```php
        $adapterOptions = $this->getOptions() + [
            'attr_errmode' => PDO::ERRMODE_EXCEPTION,
        ];
        if (isset($adapterOptions['attr_persistent'])) {
          $driverOptions[PDO::ATTR_PERSISTENT] = $adapterOptions['attr_persistent'];
        }
```

This way we are following DRY principles.

2022-05-21 06:51 UTC, paulermo commented
> Does attr_persistent work for SQL Server? If not, would there be any harm in passing it as an option anyway?

No, SQL Server does not support persistent connections. And that's why I have moved the setting of driver attribute out from PDOAdapter to specific MySQL, Postgres and SQLite. For SQL Server nothing changes in comparison to current behavior.

> This way we are following DRY principles.

Yes, that was my first solution (https://github.com/cakephp/phinx/pull/2092/commits/7a49fa25bed3b4128d0afe16481043cd2048d852), but I have found that it could break SQL server functionality and moved it out in https://github.com/cakephp/phinx/pull/2092/commits/2b860620b4d22eda9d821d43778c731a0f25fc9c.

2022-07-04 15:24 UTC, MasterOdin approved these changes

2022-07-04 15:28 UTC, MasterOdin commented
Alright, I found https://github.com/Microsoft/msphpsql/issues/65 which confirms that setting that will in fact cause the driver to throw an exception, so we cannot set it for all drivers. I'm fine with just ignoring it for mssql as opposed to throwing an exception like `cakephp/database` does.

2022-07-04 15:36 UTC, merged

2022-07-04 16:53 UTC, othercorey commented
We have a small discussions on this in the phinx-dev channel. Leaving it up to @markstory still, but @MasterOdin had some thoughts after I explained the naming alignment.

2022-07-04 16:58 UTC, MasterOdin commented
I've opened #2097 to discuss the branch switch and can carry this conversation there.