Pass environment to seed from manager.
cakephp/phinx pull request #2102
Opened 2022-08-23 10:38 UTC by martenb

2022-08-23 10:40 UTC, dereuromark commented on src/Phinx/Migration/Manager.php
> +    public function getSeeds(string $environment)
param docblock needs adjustment

2022-08-23 11:14 UTC, dereuromark approved these changes
Looks good to me

2022-08-24 01:40 UTC, MasterOdin commented
@martenb could you rebase this against the `0.next` branch instead of `0.x` as while I'm not sure how many people have created custom managers, this is still editing the public interface, and so is a BC break.

2022-08-24 06:24 UTC, martenb commented
@MasterOdin rebased

2022-08-24 14:56 UTC, MasterOdin requested changes
some minor nits, and then I think good to merge :+1:

2022-08-24 14:56 UTC, MasterOdin commented on src/Phinx/Seed/AbstractSeed.php
> +    public function getEnvironment()
```suggestion
    public function getEnvironment(): string
```

2022-08-24 14:56 UTC, MasterOdin commented on src/Phinx/Seed/SeedInterface.php
> +     * @return \Phinx\Seed\SeedInterface
```suggestion
     * @return $this
```

2022-08-24 14:56 UTC, MasterOdin commented on src/Phinx/Seed/SeedInterface.php
> +    public function getEnvironment();
```suggestion
    public function getEnvironment(): string;
```

2022-08-25 04:45 UTC, MasterOdin approved these changes

2022-08-25 04:45 UTC, merged