Add existing comment to column-object
cakephp/phinx pull request #2174
Opened 2023-02-06 13:10 UTC by alex-jonas

2023-02-09 08:58 UTC, dereuromark commented
Looks good to me

2023-02-09 09:02 UTC, othercorey commented
Looks ok to me. Do we have a test harness for this information we can add comments to?

2023-02-09 13:29 UTC, MasterOdin requested changes
Please add a row for testing the comment field to this test:

https://github.com/cakephp/phinx/blob/cea47f64fcf9dbbd93b4bb3c80e62730d8594736/tests/Phinx/Db/Adapter/MysqlAdapterTest.php#L1311

You are right we don't set the comment for any of the adapters I think. Would you want to take a stab at adding that in for them?

2023-02-17 16:20 UTC, alex-jonas commented
> Would you want to take a stab at adding that in for them?

Sorry, have not much idea about the other adapters

2023-03-01 08:22 UTC, Sinepel approved these changes

2023-03-01 13:58 UTC, dereuromark approved these changes

2023-03-01 14:02 UTC, MasterOdin approved these changes

2023-03-01 14:03 UTC, merged