Add deferrable constraints management for PSQL
cakephp/phinx pull request #2322
Opened 2024-11-25 16:18 UTC by JulienChavee

Hello,

With this PR, I am trying to implement the deferrable constraints management for PSQL, related to issue #1665.
This is my first PR here, let me know what I can improve, happy to contribute into it.

2024-11-26 02:33 UTC, MasterOdin approved these changes

2024-11-26 02:33 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PostgresAdapter.php
Can you modify https://github.com/JulienChavee/phinx/blob/809ae6b71053c29d17b605cbc30f9bb3bbc1ce62/src/Phinx/Db/Adapter/PostgresAdapter.php#L963 and have it set the appropriate `deferrable` value? Looking at https://www.postgresql.org/docs/current/infoschema-table-constraints.html, I think that this can be done by selecting `is_deferrable` and `initially_deferred` from the `information_schema.table_constraints` table.

2024-11-26 02:33 UTC, MasterOdin requested changes
Whoops, hit the wrong button. See above for requested change. Thanks for making this PR to improve phinx!

2024-11-26 10:02 UTC, JulienChavee commented on src/Phinx/Db/Adapter/PostgresAdapter.php
Sure I can look to add that.
Any reason to make this function protected and not public? I could use it in the PostgresAdapterTest to verify the deferrable status of the FK created.

Also, would you prefer to have both values like
```
is_deferrable -> true/false
initially_deferred -> true/false
```

Or having as you proposed a `deferrable` with either DEFERRED/IMMEDIATE/NOT_DEFERRED?

2024-11-29 20:30 UTC, MasterOdin commented on src/Phinx/Db/Adapter/PostgresAdapter.php
Sorry, that was a bad suggestion. I had thought that `getForeignKeys` was public and also returned `ForeignKey` object, and so would just add to that, but since it's not public and doesn't return that, then don't want the change for now.

Making it public is something we could do, but I'd want to then modify it to be like `getColumns` where it returns an array of objects, vs an array of associative arrays.

2024-11-29 20:30 UTC, MasterOdin approved these changes

2024-11-30 18:56 UTC, merged

2024-11-30 18:56 UTC, MasterOdin commented
Thanks for your contribution!